apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/l-and-d/lnd
    targetRevision: main
    path: helm/services/ld-api-gateway
    helm:
      releaseName: api-gateway
      valueFiles:
      - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true